-- 一括ドロップ
DROP TABLE ORDER_DETAIL IF EXISTS;
DROP TABLE ORDER_TRAN IF EXISTS;
DROP TABLE CUSTOMER IF EXISTS;
DROP TABLE BOOK IF EXISTS;
DROP TABLE STOCK IF EXISTS;
DROP TABLE CATEGORY IF EXISTS;
DROP TABLE PUBLISHER IF EXISTS;


